2022-01-25 23:28:16,722 - [INFO] - src.file_operations - (file_operations.py).load_model(46) - Loading model from the directory
2022-01-25 23:28:16,723 - [ERROR] - src.file_operations - (file_operations.py).load_model(54) - Exception occured in load_model method of the Model_Finder class. Exception message:  [Errno 2] No such file or directory: 'C:\\Home\\Git\\cementstrength\\data\\models\\KMeans\\.\\sav'
2022-01-25 23:30:45,344 - [INFO] - src.file_operations - (file_operations.py).load_model(46) - Loading model from the directory
2022-01-25 23:30:45,345 - [ERROR] - src.file_operations - (file_operations.py).load_model(54) - Exception occured in load_model method of the Model_Finder class. Exception message:  [Errno 2] No such file or directory: 'C:\\Home\\Git\\cementstrength\\data\\models\\KMeans\\KMeans\\.\\sav'
2022-01-25 23:31:56,217 - [INFO] - src.file_operations - (file_operations.py).load_model(46) - Loading model from the directory
2022-01-25 23:31:56,235 - [INFO] - src.file_operations - (file_operations.py).load_model(51) - Model File KMeans loaded.
2022-01-25 23:32:57,983 - [INFO] - src.file_operations - (file_operations.py).load_model(46) - Loading model from the directory
2022-01-25 23:32:57,984 - [INFO] - src.file_operations - (file_operations.py).load_model(51) - Model File KMeans loaded.
2022-01-25 23:33:39,672 - [INFO] - src.file_operations - (file_operations.py).load_model(46) - Loading model from the directory
2022-01-25 23:33:39,673 - [INFO] - src.file_operations - (file_operations.py).load_model(51) - Model File KMeans loaded.
2022-01-25 23:36:26,077 - [INFO] - src.file_operations - (file_operations.py).load_model(46) - Loading model from the directory
2022-01-25 23:36:26,077 - [INFO] - src.file_operations - (file_operations.py).load_model(51) - Model File KMeans loaded.
2022-01-25 23:36:59,451 - [INFO] - src.file_operations - (file_operations.py).load_model(46) - Loading model from the directory
2022-01-25 23:36:59,452 - [INFO] - src.file_operations - (file_operations.py).load_model(51) - Model File KMeans loaded.
2022-01-25 23:39:33,705 - [INFO] - src.file_operations - (file_operations.py).load_model(46) - Loading model from the directory
2022-01-25 23:39:33,706 - [INFO] - src.file_operations - (file_operations.py).load_model(51) - Model File KMeans loaded.
2022-01-25 23:40:43,467 - [INFO] - src.file_operations - (file_operations.py).load_model(46) - Loading model from the directory
2022-01-25 23:40:43,468 - [INFO] - src.file_operations - (file_operations.py).load_model(51) - Model File KMeans loaded.
2022-01-25 23:44:27,568 - [INFO] - src.file_operations - (file_operations.py).load_model(46) - Loading model from the directory
2022-01-25 23:44:34,824 - [INFO] - src.file_operations - (file_operations.py).load_model(51) - Model File KMeans loaded.
2022-01-25 23:57:32,233 - [INFO] - src.file_operations - (file_operations.py).load_model(46) - Loading model from the directory
2022-01-25 23:57:32,234 - [INFO] - src.file_operations - (file_operations.py).load_model(51) - Model File KMeans loaded.
2022-01-25 23:57:32,821 - [INFO] - src.file_operations - (file_operations.py).find_correct_model_file(64) - Get the correct model file based on the cluster number
2022-01-25 23:57:32,822 - [ERROR] - src.file_operations - (file_operations.py).find_correct_model_file(79) - Unable to get the correct model based on cluster'FileOperations' object has no attribute 'model_name'
